package com.es.datamigration.mapper;

import com.es.datamigration.model.TbArticleDO;

import java.util.List;

public interface TbArticleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbggenerated Wed Aug 22 10:38:26 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbggenerated Wed Aug 22 10:38:26 CST 2018
     */
    int insert(TbArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbggenerated Wed Aug 22 10:38:26 CST 2018
     */
    int insertSelective(TbArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbggenerated Wed Aug 22 10:38:26 CST 2018
     */
    TbArticleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbggenerated Wed Aug 22 10:38:26 CST 2018
     */
    int updateByPrimaryKeySelective(TbArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbggenerated Wed Aug 22 10:38:26 CST 2018
     */
    int updateByPrimaryKey(TbArticleDO record);

    /**
     * 查询所有数据列表
     * @return
     */
    List<TbArticleDO> selectAll();

}
